// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '<REPLACE WITH YOUR APIKEY>',
    appId: '<REPLACE WITH YOUR APPID>',
    messagingSenderId: '<REPLACE WITH YOUR MESSAGING-SENDER-ID>',
    projectId: '<REPLACE WITH YOUR PROJECT-ID>',
    authDomain: '<REPLACE WITH YOUR AUTH-DOMAIN>',
    storageBucket: '<REPLACE WITH YOUR STORAGE-BUCKET>',
    measurementId: '<REPLACE WITH YOUR MEASUREMENT-ID>',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '<REPLACE WITH YOUR APIKEY>',
    appId: '<REPLACE WITH YOUR APPID>',
    messagingSenderId: '<REPLACE WITH YOUR MESSAGING-SENDER-ID>',
    projectId: '<REPLACE WITH YOUR PROJECT-ID>',
    storageBucket: '<REPLACE WITH YOUR STORAGE-BUCKET>',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '<REPLACE WITH YOUR APIKEY>',
    appId:'<REPLACE WITH YOUR APPID>',
    messagingSenderId: '<REPLACE WITH YOUR MESSAGING-SENDER-ID>',
    projectId: '<REPLACE WITH YOUR PROJECT-ID>',
    storageBucket: '<REPLACE WITH YOUR STORAGE-BUCKET>',
    iosBundleId:  '<REPLACE WITH YOUR IOS-BUNDLE-ID>',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '<REPLACE WITH YOUR APIKEY>',
    appId:'<REPLACE WITH YOUR APPID>',
    messagingSenderId: '<REPLACE WITH YOUR MESSAGING-SENDER-ID>',
    projectId: '<REPLACE WITH YOUR PROJECT-ID>',
    storageBucket: '<REPLACE WITH YOUR STORAGE-BUCKET>',
    iosBundleId:  '<REPLACE WITH YOUR IOS-BUNDLE-ID>',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: '<REPLACE WITH YOUR APIKEY>',
    appId: '<REPLACE WITH YOUR APPID>',
    messagingSenderId: '<REPLACE WITH YOUR MESSAGING-SENDER-ID>',
    projectId: '<REPLACE WITH YOUR PROJECT-ID>',
    authDomain: '<REPLACE WITH YOUR AUTH-DOMAIN>',
    storageBucket: '<REPLACE WITH YOUR STORAGE-BUCKET>',
    measurementId: '<REPLACE WITH YOUR MEASUREMENT-ID>',
  );
}
